spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/dev/backend/data-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true      # JDBC 로그 활성화
      multiline: true           # MultiLineFormat 자동 적용
      logging: slf4j            # Slf4JLogger 사용
